let data={};
let lang=localStorage.getItem('1dd-lang')||'th';
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

async function loadContent(){
  try{const r=await fetch('content.json',{cache:'no-store'});data=await r.json();}
  catch(e){console.error(e);return;}
  applySeo(); setupLanguage(); renderHero(); renderBenefits(); renderProducts(); renderComparison(); renderBA(); renderSteps(); renderReviews(); renderServices(); renderFaq(); setupBooking(); setupMap(); setupNav(); setupChat(); renderSchema(); setupPwa();
}
function t(obj,key){if(typeof obj==='string') return obj; return obj?.[lang]||obj?.th||obj?.en||key||''}
function applySeo(){document.title=data.seo?.title||document.title;const d=document.querySelector('meta[name=description]');if(d)d.content=data.seo?.description||d.content}
function setupLanguage(){
  const btn=$('#langToggle');btn.textContent=lang==='th'?'EN':'TH';
  const apply=()=>{$$('[data-th]').forEach(el=>{el.textContent=el.dataset[lang]||el.dataset.th});document.documentElement.lang=lang;btn.textContent=lang==='th'?'EN':'TH';};apply();
  btn.onclick=()=>{lang=lang==='th'?'en':'th';localStorage.setItem('1dd-lang',lang);apply();renderHero(true);renderProducts();renderComparison();renderBenefits();renderSteps();renderReviews();renderServices();renderFaq();};
}
function renderHero(keep=false){let i=0,timer;const slides=data.hero||[];const bg=$('#heroBg'),dots=$('#heroDots');dots.innerHTML='';slides.forEach((_,n)=>{const b=document.createElement('button');b.ariaLabel=`Slide ${n+1}`;b.onclick=()=>show(n);dots.append(b)});function show(n){i=(n+slides.length)%slides.length;const s=slides[i];bg.style.backgroundImage=`url('${s.image}')`;$('#heroEyebrow').textContent=t(s.eyebrow);$('#heroTitle').textContent=t(s.title);$('#heroSubtitle').textContent=t(s.subtitle);[...dots.children].forEach((d,x)=>d.classList.toggle('active',x===i));clearInterval(timer);timer=setInterval(()=>show(i+1),6500)}show(0)}
function renderBenefits(){$('#benefits').innerHTML=(data.benefits||[]).map((b,i)=>`<article class="benefit-card"><span class="eyebrow gold">0${i+1}</span><h3>${esc(t(b.title))}</h3><p>${esc(t(b.text))}</p></article>`).join('')}
function renderProducts(){$('#productGrid').innerHTML=(data.products||[]).map((p,i)=>`<article class="product-card"><div class="product-media"><span class="product-badge">${esc(p.badge)}</span><img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy"></div><div class="product-body"><p class="eyebrow gold">${esc(p.badge)}</p><h3>${esc(p.name)}</h3><p>${esc(t(p.description))}</p><div class="product-price">${esc(p.price)} บาท</div><ul class="product-features">${(p.features||[]).map(x=>`<li>${esc(t(x))}</li>`).join('')}</ul><a class="btn btn-outline" href="#booking">${lang==='th'?'สนใจรุ่นนี้':'Ask about this model'}</a></div></article>`).join('')}
function renderComparison(){const rows=data.comparison?.rows||[];const products=data.products||[];$('#comparisonTable').innerHTML=`<thead><tr><th>${lang==='th'?'หัวข้อ':'Feature'}</th>${products.map(p=>`<th>${esc(p.name)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(t(r.label))}</td>${r.values.map(v=>`<td>${esc(t(v))}</td>`).join('')}</tr>`).join('')}</tbody>`}
let baIndex=0;function renderBA(){const arr=data.beforeAfter||[];const range=$('#baRange'),layer=$('#baBeforeLayer'),handle=$('#baHandle'),wrap=document.querySelector('.ba-compare');function syncWidth(){if(wrap)wrap.style.setProperty('--ba-width',wrap.clientWidth+'px')}function pos(v){layer.style.width=v+'%';handle.style.left=v+'%'}range.oninput=e=>pos(e.target.value);window.addEventListener('resize',syncWidth);function show(n){baIndex=(n+arr.length)%arr.length;const x=arr[baIndex];$('#baBefore').src=x.before;$('#baAfter').src=x.after;$('#baTitle').textContent=t(x.title);$('#baText').textContent=t(x.text);range.value=50;syncWidth();pos(50)}$('#baPrev').onclick=()=>show(baIndex-1);$('#baNext').onclick=()=>show(baIndex+1);show(0)}
function renderSteps(){$('#steps').innerHTML=(data.process||[]).map((x,i)=>`<article class="step"><strong>${i+1}</strong><p>${esc(t(x))}</p></article>`).join('')}
let reviewIndex=0,reviewTimer;function renderReviews(){const arr=data.reviews||[],card=$('#reviewCard'),dots=$('#reviewDots');dots.innerHTML=arr.map((_,i)=>`<button aria-label="Review ${i+1}"></button>`).join('');[...dots.children].forEach((b,i)=>b.onclick=()=>show(i));function show(n){reviewIndex=(n+arr.length)%arr.length;const r=arr[reviewIndex];card.innerHTML=`<span class="premium-ribbon">PREMIUM</span><img src="${esc(r.image)}" alt="${esc(r.name)}" loading="lazy"><div class="review-copy"><div class="stars">★★★★★</div><h3>${esc(r.name)}</h3><blockquote>“${esc(t(r.text))}”</blockquote><a class="btn btn-gold" href="#booking">${lang==='th'?'จองคิวเลย':'Book now'}</a></div>`;[...dots.children].forEach((d,i)=>d.classList.toggle('active',i===reviewIndex));clearInterval(reviewTimer);reviewTimer=setInterval(()=>show(reviewIndex+1),6000)}$('#reviewPrev').onclick=()=>show(reviewIndex-1);$('#reviewNext').onclick=()=>show(reviewIndex+1);show(0)}
function renderServices(){$('#serviceGrid').innerHTML=(data.services||[]).map(s=>`<article class="service-card"><div class="eyebrow gold">${esc(s.icon||'✦')}</div><h3>${esc(t(s.title))}</h3><p>${esc(t(s.text))}</p></article>`).join('')}
function renderFaq(){$('#faqList').innerHTML=(data.faq||[]).map((x,i)=>`<article class="faq-item"><button aria-expanded="false"><span>${esc(t(x.q))}</span><b>+</b></button><div class="faq-answer">${esc(t(x.a))}</div></article>`).join('');$$('.faq-item button').forEach(b=>b.onclick=()=>{const item=b.parentElement,open=item.classList.toggle('open');b.setAttribute('aria-expanded',open);b.querySelector('b').textContent=open?'−':'+'})}
function setupBooking(){const f=data.googleForm||{},link=$('#googleFormLink'),wrap=$('#googleFormEmbedWrap');link.href=f.formUrl||'#';const use=f.enableEmbed&&String(f.embedUrl).startsWith('http');if(use){wrap.hidden=false;wrap.innerHTML=`<iframe class="google-form-frame" src="${esc(f.embedUrl)}" title="1DD STUDIO Booking Google Form" loading="lazy"></iframe>`}const line=data.site.lineAddUrl||`https://line.me/ti/p/~${data.site.line}`;['lineLink','floatingLine','mobileLine'].forEach(id=>{const el=$('#'+id);if(el)el.href=line});$('#lineQr').src=data.site.lineQr||'line-qr-mozzjro.png';$('#waLink').href=`https://wa.me/${data.site.whatsapp||''}`}
function setupMap(){const frame=$('#mapFrame'),link=$('#mapOpenLink');frame.src=data.site.mapEmbed||'';link.href=data.site.map||'#'}
function setupNav(){const btn=$('.nav-toggle'),nav=$('.nav');btn.onclick=()=>{const o=nav.classList.toggle('open');btn.setAttribute('aria-expanded',o)};nav.onclick=e=>{if(e.target.tagName==='A'){nav.classList.remove('open');btn.setAttribute('aria-expanded','false')}}}
function setupChat(){const panel=$('#chatPanel'),body=$('#chatBody'),form=$('#chatForm'),input=$('#chatInput'),qs=$('#quickQuestions');const quick=lang==='th'?['ราคาเท่าไหร่','ใช้เวลากี่ชั่วโมง','ต่างจังหวัดได้ไหม','ดูแลยังไง']:['What are the prices?','How long does it take?','Do you serve other provinces?','How do I care for it?'];qs.innerHTML=quick.map(q=>`<button type="button">${q}</button>`).join('');const answer=q=>{const s=q.toLowerCase();if(/ราคา|price/.test(s))return lang==='th'?'มี 3 รุ่น: 8,000 / 15,000 / 18,000 บาท ดูรายละเอียดในส่วนสินค้าได้เลยครับ':'There are 3 packages: 8,000 / 15,000 / 18,000 THB.';if(/ชั่วโมง|เวลา|long|time/.test(s))return lang==='th'?'ขั้นตอนติดตั้งและปรับทรงใช้เวลาประมาณ 2 ชั่วโมง ขึ้นกับงานของแต่ละคนครับ':'Installation and styling take about 2 hours depending on the case.';if(/ต่างจังหวัด|province|nationwide/.test(s))return lang==='th'?'รองรับลูกค้าต่างจังหวัด สามารถส่งรูปและคุยสเปกออนไลน์ก่อนจองได้ครับ':'Yes. Out-of-province customers can send photos and discuss specifications online.';if(/ดูแล|care|ล้าง/.test(s))return lang==='th'?'หลังติดตั้งร้านจะแนะนำวิธีล้าง จัดทรง และนัดดูแลตามสภาพการใช้งานครับ':'We provide washing, styling and maintenance guidance after installation.';if(/จอง|book/.test(s))return lang==='th'?'กดปุ่มจองคิวด้านล่างเพื่อกรอก Google Form ได้เลยครับ':'Use the booking button below to submit the Google Form.';return lang==='th'?'สอบถามรายละเอียดเฉพาะเคสได้ทาง LINE: mozzjro หรือโทร 0895490884 ครับ':'For a case-specific answer, contact LINE: mozzjro or call 0895490884.'};function send(q){if(!q.trim())return;body.insertAdjacentHTML('beforeend',`<div class="user-msg">${esc(q)}</div>`);setTimeout(()=>{body.insertAdjacentHTML('beforeend',`<div class="bot-msg">${esc(answer(q))}</div>`);body.scrollTop=body.scrollHeight},250);body.scrollTop=body.scrollHeight}$('#chatOpen').onclick=()=>{panel.classList.add('open');panel.setAttribute('aria-hidden','false')};$('#chatClose').onclick=()=>{panel.classList.remove('open');panel.setAttribute('aria-hidden','true')};qs.onclick=e=>{if(e.target.tagName==='BUTTON')send(e.target.textContent)};form.onsubmit=e=>{e.preventDefault();send(input.value);input.value=''}}
function renderSchema(){const s={"@context":"https://schema.org","@type":"HairSalon","name":data.site.name,"telephone":data.site.phone,"address":{"@type":"PostalAddress","addressLocality":"Surat Thani","addressCountry":"TH"},"url":location.origin,"image":`${location.origin}/hero-1.jpg`,"priceRange":"฿฿","sameAs":[data.site.facebook,data.site.tiktok]};$('#schemaJson').textContent=JSON.stringify(s)}
function setupPwa(){if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}))}
loadContent();
